{% set name = "foxes-opt" %}
{% set version = "0.2.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/foxes-opt/archive/v{{ version }}.tar.gz
  sha256: c168e0e32c196e5d6fde674bee717c0e17797ac621d47096d82b293f8558b558

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - foxes >=1.2
    - iwopy >=0.3
    - pymoo >=0.6

test:
  imports:
    - foxes_opt
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/foxes-opt
  summary: Wind farm optimization functionality for foxes
  description: |
    This package provides optimization functionality for the
    wind farm and wake modelling package foxes. It is based
    on the optimization interface package iwopy, and enables the
    user to run fast vectorized and flexible optimizations of 
    wind farm layouts, wind farm control parameters, or any other
    set of related model parameters.
  license: MIT
  license_file: LICENSE
  doc_url: https://fraunhoferiwes.github.io/foxes-opt/index.html
  dev_url: https://github.com/FraunhoferIWES/foxes-opt

extra:
  recipe-maintainers:
    - SchmJo
