{% set name = "foxes-opt" %}
{% set version = "0.7.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/foxes-opt/archive/v{{ version }}.tar.gz
  sha256: 92d9b2a6ad1eb9bea2c2a59e0f7cbdeff00542b18380fd4e6d5e784815483192

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - foxes_opt_yaml = foxes_opt.input.yaml.yaml:foxes_opt_yaml

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - foxes >=1.5.1
    - iwopy >=0.3.1
    - pymoo >=0.6
    - netcdf4 >=1.7

test:
  imports:
    - foxes_opt
  requires:
    - python {{ python_min }}
    - pip
    - pytest >=0.7
    - h5netcdf >=1.0
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/foxes-opt
  summary: Wind farm optimization functionality for foxes
  description: |
    This package provides optimization functionality for the
    wind farm and wake modelling package foxes. It is based
    on the optimization interface package iwopy, and enables the
    user to run fast vectorized and flexible optimizations of 
    wind farm layouts, wind farm control parameters, or any other
    set of related model parameters.
  license: MIT
  license_file: LICENSE
  doc_url: https://fraunhoferiwes.github.io/foxes-opt/index.html
  dev_url: https://github.com/FraunhoferIWES/foxes-opt

extra:
  recipe-maintainers:
    - SchmJo
